import { Product, ThreadColor, EmbroideryFont, Order } from './types';

export const THREAD_COLORS: ThreadColor[] = [
  { id: 'gold', name: 'Gilded 24K Gold', hex: '#C5A059', isMetallic: true, sheen: 'High Gloss Metallic' },
  { id: 'silver', name: 'Sterling Silver', hex: '#D1D5DB', isMetallic: true, sheen: 'Silk Sheen' },
  { id: 'champagne', name: 'Champagne Silk', hex: '#E6D7BD', sheen: 'Soft Satin' },
  { id: 'alabaster', name: 'Alabaster Ivory', hex: '#F9F6EE', sheen: 'Matte Cotton' },
  { id: 'forest', name: 'Deep Forest Moss', hex: '#2C4431', sheen: 'Rich Luster' },
  { id: 'burgundy', name: 'Imperial Burgundy', hex: '#631B2A', sheen: 'Velvet Satin' },
  { id: 'obsidian', name: 'Midnight Obsidian', hex: '#191919', sheen: 'High Contrast' },
  { id: 'terracotta', name: 'Sunbaked Terracotta', hex: '#B85C38', sheen: 'Earthy Warmth' },
  { id: 'azure', name: 'Atelier French Blue', hex: '#2A4D69', sheen: 'Silk Luster' },
  { id: 'lavender', name: 'Wisteria Lavender', hex: '#9E8FB2', sheen: 'Delicate Sheen' },
];

export const EMBROIDERY_FONTS: EmbroideryFont[] = [
  { id: 'gothic', name: 'Archival Heavy Block', previewClass: 'font-display text-lg uppercase tracking-wider', fontFamily: 'Bebas Neue, Impact, sans-serif', category: 'gothic' },
  { id: 'sans', name: 'Street Grotesk Mono', previewClass: 'font-grotesk uppercase tracking-[0.2em] font-bold', fontFamily: 'Space Grotesk, sans-serif', category: 'sans' },
  { id: 'varsity', name: 'Collegiate Heavy Varsity', previewClass: 'font-mono font-extrabold tracking-widest', fontFamily: 'JetBrains Mono, monospace', category: 'varsity' },
  { id: 'script', name: 'Urban Signature Script', previewClass: 'font-sans italic font-bold tracking-wide', fontFamily: 'system-ui, cursive, sans-serif', category: 'script' },
  { id: 'serif', name: 'Vintage Street Serif', previewClass: 'font-serif uppercase tracking-widest font-bold', fontFamily: 'Times New Roman, serif', category: 'serif' },
];

export const TSHIRT_COLORS = [
  { name: 'Bone White', hex: '#F5F2EB', bgClass: 'bg-[#F5F2EB]', border: 'border-[#E3DFD5]' },
  { name: 'Sand Drift', hex: '#E8DFD1', bgClass: 'bg-[#E8DFD1]', border: 'border-[#D4C9B8]' },
  { name: 'Vintage Washed Onyx', hex: '#262524', bgClass: 'bg-[#262524]', border: 'border-[#3D3B39]' },
  { name: 'Forest Sage', hex: '#4A5B4E', bgClass: 'bg-[#4A5B4E]', border: 'border-[#38483B]' },
  { name: 'Terracotta Clay', hex: '#9E5842', bgClass: 'bg-[#9E5842]', border: 'border-[#824431]' },
  { name: 'Midnight Navy', hex: '#1C2735', bgClass: 'bg-[#1C2735]', border: 'border-[#2C3B4E]' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'The Sovereign Dragon Embroidered Boxy Tee',
    slug: 'sovereign-dragon-embroidered-tee',
    description: 'High-density 65,000-stitch intricate dragon crest crafted on our bespoke 240 GSM organic pima cotton heavyweight tee.',
    story: 'Engineered over 14 hours of embroidery digitizing, using tri-blend metallic gold and midnight silk threads. Features reinforced collar binding and drop-shoulder relaxed silhouette.',
    basePrice: 2499,
    salePrice: 2199,
    gsm: 240,
    fabric: '100% Combed Heavyweight Pima Cotton',
    fit: 'Boxy Luxury Atelier Silhouette',
    isCustomizable: true,
    category: 'Drop 01 / Heritage',
    isFeatured: true,
    inStock: true,
    stitchCount: 65400,
    threadColorsUsed: ['Gilded 24K Gold', 'Imperial Burgundy', 'Midnight Obsidian'],
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1000&q=80',
    ],
    variants: [
      { id: 'v1-s', size: 'S', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'SDRG-BW-S', stockCount: 14 },
      { id: 'v1-m', size: 'M', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'SDRG-BW-M', stockCount: 22 },
      { id: 'v1-l', size: 'L', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'SDRG-BW-L', stockCount: 18 },
      { id: 'v1-xl', size: 'XL', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'SDRG-BW-XL', stockCount: 9 },
      { id: 'v1-s-bk', size: 'S', colorName: 'Vintage Washed Onyx', colorHex: '#262524', sku: 'SDRG-BK-S', stockCount: 12 },
      { id: 'v1-m-bk', size: 'M', colorName: 'Vintage Washed Onyx', colorHex: '#262524', sku: 'SDRG-BK-M', stockCount: 28 },
      { id: 'v1-l-bk', size: 'L', colorName: 'Vintage Washed Onyx', colorHex: '#262524', sku: 'SDRG-BK-L', stockCount: 16 },
      { id: 'v1-xl-bk', size: 'XL', colorName: 'Vintage Washed Onyx', colorHex: '#262524', sku: 'SDRG-BK-XL', stockCount: 5 },
    ]
  },
  {
    id: 'prod-2',
    name: 'Botanical Herbarium Flora Embroidered Tee',
    slug: 'botanical-herbarium-flora-tee',
    description: 'Fine satin-stitch wild flora motif positioned delicately across the left chest with trailing micro-stem accents.',
    story: 'Inspired by 18th-century French botanical illustrations. Rendered in five tonal shades of moss and sage threads with champagne pistils.',
    basePrice: 1999,
    gsm: 240,
    fabric: '100% Ring-Spun Organic Cotton',
    fit: 'Tailored Relaxed Fit',
    isCustomizable: true,
    category: 'Drop 01 / Heritage',
    isFeatured: true,
    inStock: true,
    stitchCount: 28200,
    threadColorsUsed: ['Deep Forest Moss', 'Champagne Silk', 'Sunbaked Terracotta'],
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1000&q=80',
    ],
    variants: [
      { id: 'v2-s', size: 'S', colorName: 'Forest Sage', colorHex: '#4A5B4E', sku: 'BTH-FS-S', stockCount: 20 },
      { id: 'v2-m', size: 'M', colorName: 'Forest Sage', colorHex: '#4A5B4E', sku: 'BTH-FS-M', stockCount: 30 },
      { id: 'v2-l', size: 'L', colorName: 'Forest Sage', colorHex: '#4A5B4E', sku: 'BTH-FS-L', stockCount: 15 },
      { id: 'v2-xl', size: 'XL', colorName: 'Forest Sage', colorHex: '#4A5B4E', sku: 'BTH-FS-XL', stockCount: 8 },
      { id: 'v2-m-sand', size: 'M', colorName: 'Sand Drift', colorHex: '#E8DFD1', sku: 'BTH-SD-M', stockCount: 25 },
      { id: 'v2-l-sand', size: 'L', colorName: 'Sand Drift', colorHex: '#E8DFD1', sku: 'BTH-SD-L', stockCount: 18 },
    ]
  },
  {
    id: 'prod-3',
    name: 'Atelier Roman Monogram Heavyweight Blank Tee',
    slug: 'atelier-bespoke-custom-blank-tee',
    description: 'Our signature blank canvas: pre-shrunk 260 GSM French terry cotton engineered specifically for custom bespoke embroidery.',
    story: 'Dense knit structure resists fabric puckering under dense needle strikes. The ultimate foundation to apply your personal initials, crest, or custom artwork.',
    basePrice: 1499,
    gsm: 260,
    fabric: '260 GSM Micro-French Terry Cotton',
    fit: 'Boxy Heavyweight Drop-Shoulder',
    isCustomizable: true,
    category: 'Custom Studio Blanks',
    isFeatured: true,
    inStock: true,
    images: [
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
    ],
    variants: [
      { id: 'v3-s-bw', size: 'S', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'BLK-BW-S', stockCount: 45 },
      { id: 'v3-m-bw', size: 'M', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'BLK-BW-M', stockCount: 60 },
      { id: 'v3-l-bw', size: 'L', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'BLK-BW-L', stockCount: 50 },
      { id: 'v3-xl-bw', size: 'XL', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'BLK-BW-XL', stockCount: 30 },
      { id: 'v3-xxl-bw', size: 'XXL', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'BLK-BW-XXL', stockCount: 18 },
      { id: 'v3-m-vo', size: 'M', colorName: 'Vintage Washed Onyx', colorHex: '#262524', sku: 'BLK-VO-M', stockCount: 55 },
      { id: 'v3-l-vo', size: 'L', colorName: 'Vintage Washed Onyx', colorHex: '#262524', sku: 'BLK-VO-L', stockCount: 40 },
      { id: 'v3-m-mn', size: 'M', colorName: 'Midnight Navy', colorHex: '#1C2735', sku: 'BLK-MN-M', stockCount: 35 },
      { id: 'v3-m-tc', size: 'M', colorName: 'Terracotta Clay', colorHex: '#9E5842', sku: 'BLK-TC-M', stockCount: 22 },
    ]
  },
  {
    id: 'prod-4',
    name: 'Archival Renaissance Cherub Gold-Stitch Tee',
    slug: 'archival-renaissance-cherub-tee',
    description: 'Museum-grade multi-directional tatami stitch depicting a classical cherub playing a golden lyre.',
    story: 'Combines micro-satin contouring with matte ivory fill and sparkling metallic gold instrument threads for an authentic Renaissance oil painting effect in thread.',
    basePrice: 2799,
    salePrice: 2499,
    gsm: 240,
    fabric: '100% Combed Pima Cotton',
    fit: 'Relaxed Drop Shoulder',
    isCustomizable: true,
    category: 'Drop 01 / Heritage',
    isFeatured: true,
    inStock: true,
    stitchCount: 78900,
    threadColorsUsed: ['Gilded 24K Gold', 'Alabaster Ivory', 'Champagne Silk'],
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
    ],
    variants: [
      { id: 'v4-s', size: 'S', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'RNC-BW-S', stockCount: 10 },
      { id: 'v4-m', size: 'M', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'RNC-BW-M', stockCount: 16 },
      { id: 'v4-l', size: 'L', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'RNC-BW-L', stockCount: 12 },
      { id: 'v4-xl', size: 'XL', colorName: 'Bone White', colorHex: '#F5F2EB', sku: 'RNC-BW-XL', stockCount: 4 },
    ]
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'GET-2026-9812',
    customerName: 'Aarav Mehta',
    customerEmail: 'aarav.mehta@example.com',
    customerPhone: '+91 98765 43210',
    subtotal: 2499,
    customizationFee: 399,
    shippingFee: 0,
    discount: 0,
    totalAmount: 2898,
    status: 'STITCHING',
    paymentStatus: 'PAID',
    paymentGateway: 'PAYU',
    payuTxnId: 'TXN_PAYU_98129031',
    payuMihpayId: 'MIH_409182390',
    payuMode: 'UPI',
    stitchProgressPercentage: 65,
    trackingNumber: 'DELHIVERY-78901234',
    courierName: 'Delhivery Express',
    shippingAddress: {
      fullName: 'Aarav Mehta',
      phone: '+91 98765 43210',
      email: 'aarav.mehta@example.com',
      street: 'Flat 402, Signature Palms, Golf Course Road',
      landmark: 'Near Club House',
      city: 'Gurugram',
      state: 'Haryana',
      postalCode: '122002',
      country: 'India',
    },
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        product: INITIAL_PRODUCTS[0],
        variant: INITIAL_PRODUCTS[0].variants[1],
        quantity: 1,
        unitPrice: 2499,
        totalPrice: 2898,
        customEmbroidery: {
          type: 'TEXT',
          placement: 'BACK_NAPE',
          customText: 'A. MEHTA',
          fontStyle: 'Roman Heritage',
          threadColor: 'Gilded 24K Gold',
          threadColorHex: '#C5A059',
          stitchType: 'SATIN',
          customCharge: 399,
          estimatedStitches: 4500,
        }
      }
    ],
    createdAt: '2026-09-10T14:32:00Z',
    updatedAt: '2026-09-11T09:15:00Z',
  },
  {
    id: 'ord-102',
    orderNumber: 'GET-2026-9815',
    customerName: 'Priya Sharma',
    customerEmail: 'priya.s@example.com',
    customerPhone: '+91 98111 22334',
    subtotal: 1499,
    customizationFee: 599,
    shippingFee: 0,
    discount: 100,
    totalAmount: 1998,
    status: 'DIGITIZING',
    paymentStatus: 'PAID',
    paymentGateway: 'PAYU',
    payuTxnId: 'TXN_PAYU_98151244',
    payuMihpayId: 'MIH_409182991',
    payuMode: 'Credit Card',
    stitchProgressPercentage: 30,
    shippingAddress: {
      fullName: 'Priya Sharma',
      phone: '+91 98111 22334',
      email: 'priya.s@example.com',
      street: 'Villa 14, Lavelle Mansions, Ashok Nagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560001',
      country: 'India',
    },
    items: [
      {
        id: 'item-2',
        productId: 'prod-3',
        product: INITIAL_PRODUCTS[2],
        variant: INITIAL_PRODUCTS[2].variants[1],
        quantity: 1,
        unitPrice: 1499,
        totalPrice: 2098,
        customEmbroidery: {
          type: 'ARTWORK',
          placement: 'CHEST_LEFT',
          artworkNotes: 'Monochrome atelier lion crest silhouette with high stitch tension',
          stitchType: 'PUFF_3D',
          threadColor: 'Gilded 24K Gold',
          threadColorHex: '#C5A059',
          customCharge: 599,
          estimatedStitches: 11200,
          uploadedImageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=400&q=80',
        }
      }
    ],
    createdAt: '2026-09-11T08:10:00Z',
    updatedAt: '2026-09-11T10:00:00Z',
  }
];
